SYMBOL_TO_NAME = {
    "TSLA": "Tesla",
    "NVDA": "Nvidia",
    "GME": "GameStop",
    "AMC": "AMC",
    "PLTR": "Palantir",
    "COIN": "Coinbase",
    "MSTR": "MicroStrategy",
    "BYND": "Beyond Meat",
    "RIVN": "Rivian",
    "AFRM": "Affirm",
    "SOFI": "SoFi",
    "BB": "BlackBerry",
    "BBBYQ": "Bed Bath & Beyond",
    "NIO": "NIO",
    "LCID": "Lucid",
    "NKLA": "Nikola",
    "AAPL": "Apple",
    "META": "Meta",
    "SNAP": "Snap"
}
